# Terragon Autonomous SDLC Enhancement Configuration
# Continuous value discovery and prioritization system

scoring:
  # Adaptive weight configuration based on repository maturity
  weights:
    maturing:  # Current repository classification
      wsjf: 0.5
      ice: 0.2
      technicalDebt: 0.2
      security: 0.1
  
  # Value thresholds and boost factors
  thresholds:
    minScore: 15
    maxRisk: 0.7
    securityBoost: 2.0
    complianceBoost: 1.8
    performanceBoost: 1.5
    documentationPenalty: 0.6

# Discovery source configuration
discovery:
  sources:
    - gitHistory
    - staticAnalysis
    - issueTrackers
    - vulnerabilityDatabases
    - performanceMonitoring
    - codeComments
    - dependencyUpdates
  
  # Static analysis tools integration
  tools:
    staticAnalysis:
      - ruff
      - mypy  
      - bandit
      - safety
    security:
      - bandit
      - safety
      - pip-audit
    performance:
      - pytest-benchmark
      - memory-profiler
    quality:
      - black
      - isort
      - pre-commit

# Execution configuration
execution:
  maxConcurrentTasks: 1
  branchPrefix: "auto-value"
  
  # Quality gates
  testRequirements:
    minCoverage: 80
    performanceRegression: 5
    securityViolations: 0
  
  # Rollback triggers
  rollbackTriggers:
    - testFailure
    - buildFailure
    - securityViolation
    - coverageDecrease

# Value categories and their priorities
categories:
  security:
    priority: 1
    multiplier: 2.0
    autoExecute: true
  
  performance:
    priority: 2
    multiplier: 1.5
    autoExecute: true
  
  technicalDebt:
    priority: 3
    multiplier: 1.2
    autoExecute: true
  
  documentation:
    priority: 4
    multiplier: 0.8
    autoExecute: false
  
  enhancement:
    priority: 5
    multiplier: 1.0
    autoExecute: false

# Mathematical formalization specific configuration
mathematical:
  proofAssistants:
    - lean4
    - isabelle
    - coq
  
  validationThresholds:
    proofCorrectness: 100
    syntaxCorrectness: 95
    typeCheckingSuccess: 100
  
  priorityDomains:
    - algebra
    - analysis
    - topology
    - numberTheory

# Integration settings
integrations:
  github:
    autoCreatePR: true
    assignReviewers: true
    useCodeOwners: true
    
  notifications:
    slack: false
    email: false
    github: true
    
  monitoring:
    prometheus: false
    datadog: false
    sentry: false