# Pre-commit configuration for autoformalize-math-lab
# See https://pre-commit.com for more information

repos:
  # Python code formatting and linting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.lean$|\.thy$|\.v$'
      - id: end-of-file-fixer
        exclude: '\.lean$|\.thy$|\.v$'
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=10000']
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: name-tests-test
        args: ['--django']
      - id: requirements-txt-fixer

  # Python formatting with Black
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
        args: ['--line-length=88']

  # Python import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ['--profile', 'black', '--line-length=88']

  # Python linting with flake8
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=88', '--extend-ignore=E203,W503']
        additional_dependencies:
          - flake8-docstrings
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify

  # Python type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - types-redis
          - types-setuptools
        args: ['--ignore-missing-imports']

  # Security scanning with bandit
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ['-c', 'pyproject.toml']
        additional_dependencies: ['bandit[toml]']

  # Python dependency scanning
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.2
    hooks:
      - id: python-safety-dependencies-check
        files: requirements.*\.txt$

  # LaTeX formatting and linting
  - repo: https://github.com/cmhughes/latexindent.pl
    rev: V3.21
    hooks:
      - id: latexindent
        args: ['-w', '-s']
        files: '\.tex$'

  # LaTeX spell checking (optional - requires aspell)
  # - repo: https://github.com/crate-ci/typos
  #   rev: v1.16.5
  #   hooks:
  #     - id: typos
  #       files: '\.(tex|md|py)$'

  # Markdown formatting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint
        args: ['--fix']
        files: '\.md$'

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.1
    hooks:
      - id: prettier
        types: [yaml]

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        args: ['--ignore', 'DL3008', '--ignore', 'DL3009']

  # Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck

  # Commit message formatting
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.6.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # Lean 4 formatting (if lean4 toolchain is available)
  # - repo: local
  #   hooks:
  #     - id: lean4-format
  #       name: Format Lean 4 files
  #       entry: lake exe format
  #       language: system
  #       files: '\.lean$'
  #       pass_filenames: false

  # Mathematical notation consistency check
  - repo: local
    hooks:
      - id: math-notation-check
        name: Check mathematical notation consistency
        entry: python scripts/check_math_notation.py
        language: system
        files: '\.(tex|md|py)$'
        pass_filenames: true

  # Custom hook for proof validation (optional)
  # - repo: local
  #   hooks:
  #     - id: proof-validation
  #       name: Validate generated proofs
  #       entry: python scripts/validate_proofs.py
  #       language: system
  #       files: '\.(lean|thy|v)$'
  #       pass_filenames: true

# Configuration for specific hooks
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false