apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoformalize-api
  namespace: autoformalize
  labels:
    app: autoformalize-api
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: autoformalize-api
  template:
    metadata:
      labels:
        app: autoformalize-api
        version: v1
    spec:
      containers:
      - name: autoformalize-api
        image: autoformalize/math-lab:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        - name: WORKERS
          value: "4"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: cache-volume
          mountPath: /app/cache
        - name: logs-volume
          mountPath: /app/logs
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: autoformalize-cache-pvc
      - name: logs-volume
        persistentVolumeClaim:
          claimName: autoformalize-logs-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: autoformalize-api-service
  namespace: autoformalize
spec:
  selector:
    app: autoformalize-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: autoformalize-config
  namespace: autoformalize
data:
  config.yaml: |
    api:
      host: "0.0.0.0"
      port: 8000
      workers: 4
    cache:
      type: "redis"
      url: "redis://redis-service:6379"
    logging:
      level: "INFO"
      format: "json"
    monitoring:
      enabled: true
      endpoint: "/metrics"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autoformalize-hpa
  namespace: autoformalize
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: autoformalize-api
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
